# This is a config synced from hanami/template-gem repo

sources:
  - repo: hanami/template-gem
    sync:
      - ".action_hero.yml.erb"
      - ".github/FUNDING.yml"
      - ".rspec"
      - ".rubocop.yml"
      - "CODE_OF_CONDUCT.md"
      - "LICENSE.md.erb"
