# Please keep AllCops, Bundler, Style, Metrics groups and then order cops
# alphabetically
AllCops:
  SuggestExtensions: false
inherit_from:
  - https://raw.githubusercontent.com/hanami/devtools/main/.rubocop.yml
Layout/LineLength:
  Exclude:
    - Gemfile
    - 'spec/**/*.rb'
Lint/DuplicateBranch:
  Enabled: false
Lint/EmptyFile:
  Exclude:
    - 'spec/fixtures/**/*.rb'
Lint/NonLocalExitFromIterator:
  Enabled: false
Naming/HeredocDelimiterNaming:
  Enabled: false
Naming/MethodParameterName:
  AllowedNames:
    - fs
Naming/RescuedExceptionsVariableName:
  Enabled: false
Style/AccessorGrouping:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/CommentedKeyword:
  Enabled: false
Style/EmptyHeredoc:
  Enabled: false
Style/IdenticalConditionalBranches:
  Enabled: false
Style/LambdaCall:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Style/ZeroLengthPredicate:
  Enabled: false
