#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler"
require "hanami/cli"

cli = Dry::CLI.new(Hanami::CLI)
::Bundler.require(:cli) if File.exist?(ENV["BUNDLE_GEMFILE"] || "Gemfile")

cli.call
